apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fastapi-password
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    db-password: {{ .Values.sealed_secrets.fastapi.db_password }}
  template:
    metadata:
      creationTimestamp: null
      name: fastapi-password
      namespace: {{ .Release.Namespace }}
    type: Opaque
