{{- if .Values.grafana.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-password
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    admin-user: {{ .Values.sealed_secrets.grafana.user }}
    admin-password: {{ .Values.sealed_secrets.grafana.password }}
  template:
    metadata:
      creationTimestamp: null
      name: grafana-password
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}