apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-password
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    admin-password: {{ .Values.sealed_secrets.keycloak.admin_password }}
    db-password: {{ .Values.sealed_secrets.keycloak.db_password }}
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-password
      namespace: {{ .Release.Namespace }}
    type: Opaque
