apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    postgres-password: {{ .Values.sealed_secrets.postgres.password }}
  template:
    metadata:
      creationTimestamp: null
      name: postgres-password
      namespace: {{ .Release.Namespace }}
    type: Opaque
