apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-password
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    rabbitmq-password: {{ .Values.sealed_secrets.rabbitmq.password }}
    rabbitmq-erlang-cookie: {{ .Values.sealed_secrets.rabbitmq.erlang_cookie }}
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-password
      namespace: {{ .Release.Namespace }}
    type: Opaque
