apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.sealed_secrets.registry_credentials }}
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/dockerconfigjson
