{{- $Values := .Values -}}
{{- if $Values.mailhog.enabled -}}
{{- $name := "mailhog" }}
{{- with .Values.mailhog -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        image: {{ .image | quote }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 8025
        readinessProbe:
          httpGet:
            path: /
            port: 8025
        resources:
{{ toYaml .resources | indent 10 }}
{{- end }}
{{- end }}