{{- if .Values.networkpolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minio-egress-allow-keycloak
spec:
  podSelector:
    matchLabels:
      tag: minio
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 8080
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: keycloak
{{- end }}