{{- $Values := .Values -}}
{{- $Release := .Release }}
{{- range $i, $name := list "rabbitmqworkflow" "rabbitmqcluster"  }}
{{- with ( get $Values $name ) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name }}
spec:
  type: {{ .service.type }}
  ports:
  - port: {{ .service.externalPort }}
    targetPort: {{ .service.internalPort }}
    protocol: TCP
    name: {{ $name }}
  selector:
    app: {{ $name }}
{{ end }}
{{ end }}
