{{- $Values := .Values -}}
{{- $serviceName :=  "fastapi" -}}
{{- with .Values.fastapi.ingress -}}
{{- if .enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
  annotations:
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecRequestBodyAccess On
      SecAuditEngine RelevantOnly
      SecAuditLogParts ABIJDEFHZ
      SecAuditLog /var/log/modsec_audit.log

spec:
  ingressClassName: {{ .ingressClassName }}
  rules:
    {{- range $host := .hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port: 
                  number: {{ $Values.fastapi.service.externalPort }}
    {{- end -}}
  {{- if .tls }}
  tls:
{{ toYaml .tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
