apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fastapi
subjects:
- kind: ServiceAccount
  name: fastapi
roleRef:
  kind: Role
  name: fastapi
  apiGroup: rbac.authorization.k8s.io